### ISSUE TITLE
BUG: table name "j1" specified more than once

### ISSUE THREAD

**Issue by mutavci** [sqbjs/sqb#46]
when I send the request with these options
FindAllOptions:
```json

{
  "elements": [
    "id",
    "createdBy",
    "createdAt",
    "updatedBy",
    "updatedAt",
    "type",
    "scheduleId",
    "$schedule",
    "status",
    "startDateTime",
    "endDateTime",
    "patientId",
    "$patient",
    "name",
    "description",
    "phoneNumber1",
    "phoneNumber2",
    "slotIds",
    "priority",
    "cancelledAt",
    "cancelledBy",
    "cancellationReason"
  ],
  "filter": [
    {
      "$schedule.$resource.$participants.referenceId": "27b5b852-013d-49c5-be2f-5dbeb320dad0"
    }
  ],
  "limit": 10
}
```
outgoing sql query:
```sql
       .
       .
       .
       .
       T.priority AS T_PRIORITY,
       T.cancelled_at AS T_CANCELLEDAT,
       T.cancelled_by AS T_CANCELLEDBY,
       T.cancellation_reason AS T_CANCELLATIONREASON
FROM appointments T
LEFT OUTER JOIN schedules J1 ON J1.id = T.schedule_id
LEFT OUTER JOIN patients J2 ON J2.id = T.patient_id
WHERE EXISTS
    (SELECT 1
     FROM schedules K
     INNER JOIN app_resources J1 ON J1.id = K.resource_id
     INNER JOIN app_resource_participants J1 ON J1.resource_id = J1.id
     WHERE K.id = T.schedule_id
     AND J1.reference_id = $1) Params:[ '27b5b852-013d-49c5-be2f-5dbeb320dad0'
```
the error I got:
```
Error: table name "j1" specified more than once
    at /Users/panates/Documents/node_workspaces/panates/emr-server/node_modules/postgresql-client/src/protocol/PgSocket.ts:244:44
    at Backend.parse (/Users/panates/Documents/node_workspaces/panates/emr-server/node_modules/postgresql-client/src/protocol/Backend.ts:58:13)
    at PgSocket._handleData (/Users/panates/Documents/node_workspaces/panates/emr-server/node_modules/postgresql-client/src/protocol/PgSocket.ts:237:23)
    at Socket.<anonymous> (/Users/panates/Documents/node_workspaces/panates/emr-server/node_modules/postgresql-client/src/protocol/PgSocket.ts:213:50)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) 
```
Version "@sqb/**": "^4.0.1-beta.14"

**Comment by erayhanoglu** [comment]
Fixed.
